# Generated by Django 4.2 on 2025-02-17 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("newsletter", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="newsletter",
            name="background_image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="newsletter_backgrounds/",
                verbose_name="Фоновое изображение",
            ),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="font_size",
            field=models.IntegerField(default=16, verbose_name="Размер шрифта"),
        ),
        migrations.AddField(
            model_name="newsletter",
            name="text_color",
            field=models.CharField(
                default="#000000", max_length=7, verbose_name="Цвет текста"
            ),
        ),
    ]
