# Generated by Django 4.2 on 2025-02-06 16:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0001_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="price",
            unique_together=None,
        ),
        migrations.RemoveField(
            model_name="price",
            name="hair_length",
        ),
        migrations.RemoveField(
            model_name="price",
            name="master",
        ),
        migrations.RemoveField(
            model_name="price",
            name="product",
        ),
        migrations.DeleteModel(
            name="TestTable",
        ),
        migrations.AddField(
            model_name="products",
            name="hair_length",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="services.hairlength",
                verbose_name="Длина волос",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="services.masters",
                verbose_name="Мастер",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="max_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                max_digits=8,
                null=True,
                verbose_name="Максимальная цена",
            ),
        ),
        migrations.AddField(
            model_name="products",
            name="min_price",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                max_digits=8,
                verbose_name="Минимальная цена",
            ),
        ),
        migrations.DeleteModel(
            name="Price",
        ),
    ]
