# Generated by Django 4.2 on 2025-02-06 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0003_remove_products_master_products_master"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="master",
        ),
        migrations.AddField(
            model_name="products",
            name="master",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="prices",
                to="services.masters",
                verbose_name="Мастер",
            ),
        ),
    ]
