# Generated by Django 4.2 on 2025-02-06 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0004_remove_products_master_products_master"),
    ]

    operations = [
        migrations.AddField(
            model_name="masters",
            name="description",
            field=models.TextField(
                blank=True, null=True, verbose_name="Описание мастера"
            ),
        ),
    ]
