# Generated by Django 4.2 on 2025-02-06 18:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0005_masters_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="master",
        ),
        migrations.AddField(
            model_name="products",
            name="master",
            field=models.ManyToManyField(
                blank=True,
                related_name="prices",
                to="services.masters",
                verbose_name="Мастер",
            ),
        ),
    ]
