# Generated by Django 4.2 on 2025-02-06 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0006_remove_products_master_products_master"),
    ]

    operations = [
        migrations.RenameField(
            model_name="products",
            old_name="master",
            new_name="masters",
        ),
    ]
