# Generated by Django 4.2 on 2025-02-06 18:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0007_rename_master_products_masters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="products",
            name="hair_length",
        ),
        migrations.RemoveField(
            model_name="products",
            name="masters",
        ),
        migrations.RemoveField(
            model_name="products",
            name="max_price",
        ),
        migrations.RemoveField(
            model_name="products",
            name="min_price",
        ),
    ]
