# Generated by Django 4.2 on 2025-02-06 18:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "services",
            "0008_remove_products_hair_length_remove_products_masters_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Price",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "min_price",
                    models.DecimalField(
                        decimal_places=2, max_digits=8, verbose_name="Минимальная цена"
                    ),
                ),
                (
                    "max_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=8,
                        null=True,
                        verbose_name="Максимальная цена",
                    ),
                ),
                (
                    "hair_length",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="services.hairlength",
                        verbose_name="Длина волос",
                    ),
                ),
                (
                    "master",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="services.masters",
                        verbose_name="Мастер",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="prices",
                        to="services.products",
                        verbose_name="Продукт",
                    ),
                ),
            ],
            options={
                "verbose_name": "Цена",
                "verbose_name_plural": "Цены",
                "db_table": "product_price",
                "unique_together": {("product", "master", "hair_length")},
            },
        ),
    ]
