# Generated by Django 4.2 on 2025-02-06 19:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0009_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={"verbose_name": "категорию", "verbose_name_plural": "категории"},
        ),
        migrations.AlterModelOptions(
            name="hairlength",
            options={
                "verbose_name": "длину волос",
                "verbose_name_plural": "длины волос",
            },
        ),
        migrations.AlterModelOptions(
            name="price",
            options={"verbose_name": "цену", "verbose_name_plural": "цены"},
        ),
        migrations.AlterModelOptions(
            name="products",
            options={"verbose_name": "продукт", "verbose_name_plural": "продукты"},
        ),
        migrations.AlterModelOptions(
            name="productsexample",
            options={
                "verbose_name": "пример работы",
                "verbose_name_plural": "примеры работ",
            },
        ),
        migrations.AlterUniqueTogether(
            name="price",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="price",
            name="masters",
            field=models.ManyToManyField(
                related_name="prices", to="services.masters", verbose_name="Мастер"
            ),
        ),
        migrations.RemoveField(
            model_name="price",
            name="master",
        ),
    ]
