# Generated by Django 4.2 on 2025-02-06 19:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0011_masters_discount"),
    ]

    operations = [
        migrations.AlterField(
            model_name="price",
            name="max_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Максимальная цена"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="min_price",
            field=models.IntegerField(verbose_name="Минимальная цена"),
        ),
    ]
