# Generated by Django 4.2 on 2025-02-06 20:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0012_alter_price_max_price_alter_price_min_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="price",
            name="base_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Фиксированная цена"
            ),
        ),
        migrations.AlterField(
            model_name="price",
            name="masters",
            field=models.ManyToManyField(
                blank=True,
                related_name="prices",
                to="services.masters",
                verbose_name="Мастер",
            ),
        ),
    ]
