# Generated by Django 4.2 on 2025-02-06 20:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0013_price_base_price_alter_price_masters"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="price",
            name="base_price",
        ),
        migrations.AddField(
            model_name="products",
            name="base_price",
            field=models.IntegerField(
                blank=True, null=True, verbose_name="Фиксированная цена"
            ),
        ),
    ]
