# Generated by Django 4.2 on 2025-02-09 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0014_remove_price_base_price_products_base_price"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="categories",
            options={
                "ordering": ["name"],
                "verbose_name": "категорию",
                "verbose_name_plural": "категории",
            },
        ),
        migrations.AlterModelOptions(
            name="hairlength",
            options={
                "ordering": ["name"],
                "verbose_name": "длину волос",
                "verbose_name_plural": "длины волос",
            },
        ),
        migrations.AlterModelOptions(
            name="masters",
            options={
                "ordering": ["level", "name"],
                "verbose_name": "мастера",
                "verbose_name_plural": "мастера",
            },
        ),
        migrations.AlterModelOptions(
            name="price",
            options={
                "ordering": ["product__name", "min_price"],
                "verbose_name": "цену",
                "verbose_name_plural": "цены",
            },
        ),
        migrations.AlterModelOptions(
            name="products",
            options={
                "ordering": ["name"],
                "verbose_name": "продукт",
                "verbose_name_plural": "продукты",
            },
        ),
        migrations.AlterModelOptions(
            name="productsexample",
            options={
                "ordering": ["-uploaded_at"],
                "verbose_name": "пример работы",
                "verbose_name_plural": "примеры работ",
            },
        ),
        migrations.AddField(
            model_name="products",
            name="show_on_homepage",
            field=models.BooleanField(
                default=False, verbose_name="Показывать на главной"
            ),
        ),
        migrations.AlterField(
            model_name="products",
            name="base_price",
            field=models.PositiveIntegerField(
                blank=True, null=True, verbose_name="Фиксированная цена"
            ),
        ),
    ]
