# Generated by Django 4.2 on 2025-02-15 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("services", "0015_alter_categories_options_alter_hairlength_options_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="categories",
            name="bg_image",
            field=models.FileField(
                blank=True,
                null=True,
                upload_to="categories/",
                verbose_name="Фоновое изображение",
            ),
        ),
        migrations.AlterField(
            model_name="categories",
            name="svg_image",
            field=models.CharField(
                default="fonts/flaticon/svg/default.svg",
                help_text="Пример: 'icons/brows.svg'",
                max_length=255,
                verbose_name="Путь к SVG-иконке",
            ),
        ),
    ]
