# Generated by Django 4.2 on 2025-02-09 17:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="SliderContent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=250, verbose_name="Заголовок")),
                ("content", models.TextField(verbose_name="Описание контента")),
                (
                    "slider_photo",
                    models.ImageField(
                        upload_to="slider-info/", verbose_name="Фото на слайдере"
                    ),
                ),
                (
                    "link",
                    models.URLField(
                        blank=True, null=True, verbose_name="Ссылка на мероприятие"
                    ),
                ),
            ],
            options={
                "verbose_name": "слайдера",
                "verbose_name_plural": "слайдеров",
                "db_table": "slider_content",
                "ordering": ["id"],
            },
        ),
    ]
