# Generated by Django 4.2 on 2025-02-09 17:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("main", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="slidercontent",
            options={
                "ordering": ["id"],
                "verbose_name": "слайдера",
                "verbose_name_plural": "слайдеры",
            },
        ),
        migrations.RemoveField(
            model_name="slidercontent",
            name="title",
        ),
    ]
